version: '3.8'
services:
  redis:
    image: redis:7
    restart: always

  go-ingest:
    build: ./go-ingest
    ports:
      - "8080:8080"
    depends_on:
      - redis

  py-analyzer:
    build: ./py-analyzer
    ports:
      - "5000:5000"
    depends_on:
      - redis
